### ISSUE TITLE
CID in bytetrack only return 0

### ISSUE THREAD

**Issue by vietanhbui** [Kazuhito00/MOT-Tracking-by-Detection-Pipeline#3]
Test video with nanodet + bytetrack: CID only return 0

**Comment by Kazuhito00** [comment]
ByteTrack is a tracker for single class
If you want to use the multi-class extended version, please specify "mc_bytetrack".

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.
